builds:
  - id: zrok-amd64
    main: ./cmd/zrok
    binary: zrok
    ldflags: "-s -w -X github.com/openziti-test-kitchen/zrok/build.Version={{.Tag}} -X github.com/openziti-test-kitchen/zrok/build.Hash={{.ShortCommit}}"
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
    hooks:
      post: gon build/gon-amd64.hcl

  - id: zrok-arm64
    main: ./cmd/zrok
    binary: zrok
    ldflags: "-s -w -X github.com/openziti-test-kitchen/zrok/build.Version={{.Tag}} -X github.com/openziti-test-kitchen/zrok/build.Hash={{.ShortCommit}}"
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    hooks:
      post: gon build/gon-arm64.hcl
