builds:
- main: ./cmd/zrok
- ldflags: "-s -w -X github.com/openziti-test-kitchen/zrok/build.Version=${{.Tag}} -X github.com/openziti-test-kitchen/zrok/build.Hash=${{.ShortCommit}}"
- goarch:
    - amd64