version: '3'
services:
  zrok-private-access:
    # build: .
    image: docker.io/openziti/zrok
    user: root
    command: access private --bind 0.0.0.0:9191 ${ZROK_PRIVATE_ACCESS_TOKEN}
    ports:
      - 9191:9191
    stdin_open: true
    tty: true
    volumes:
    - ${HOME}/.zrok:/mnt/.zrok
    environment:
      HOME: /mnt
      PFXLOG_NO_JSON: "true"
      ZROK_PRIVATE_ACCESS_TOKEN:
  busybox:
    image: busybox
    command: >
      sh -c "while true; do 
        echo 'INFO: trying wget';
        wget -q -O - http://zrok-private-access:9191/get; 
        sleep 3; 
      done"
