version: '3'
services:
  zrok-enable-init:
    image: busybox
    command: chown -Rc 65534:65534 /mnt/.zrok
    user: root
    volumes:
    - zrok_env:/mnt/.zrok
  zrok-enable:
    depends_on: ["zrok-enable-init"]
    image: docker.io/openziti/zrok
    command: enable ${ZROK_ENABLE_TOKEN}
    stdin_open: true
    tty: true
    volumes:
    - zrok_env:/mnt/.zrok
    environment:
      HOME: /mnt
      ZROK_ENABLE_TOKEN:
      ZROK_API_ENDPOINT: https://api.staging.zrok.io/
  zrok-private-share:
    # build: .
    image: docker.io/openziti/zrok
    user: root
    command: share private --headless http://httpbin-test:8080
    depends_on: []
    volumes:
    - ${HOME}/.zrok:/mnt/.zrok
    environment:
      HOME: /mnt
      PFXLOG_NO_JSON: "true"
  zrok-test:
    image: docker.io/openziti/zrok
    command: test endpoint --verbose --address 0.0.0.0
  httpbin-test:
    image: mccutchen/go-httpbin  # 8080/tcp

volumes:
  zrok_env: