info:
  description: zrok client access
  title: zrok
  version: 1.0.0

paths:
  /account:
    post:
      tags:
        - identity
      operationId: createAccount
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/accountRequest"
      responses:
        201:
          description: account created
          schema:
            $ref: "#/definitions/accountResponse"
  /version:
    get:
      tags:
        - metadata
      operationId: version
      responses:
        200:
          description: retrieve the current server version
          schema:
            $ref: "#/definitions/version"

definitions:
  version:
    type: object
    properties:
      version:
        type: string
  accountRequest:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
  accountResponse:
    type: object
    properties:
      apiToken:
        type: string

produces:
- application/zrok.v1+json
consumes:
- application/zrok.v1+json
schemes:
- http
swagger: "2.0"
