info:
  description: Client access service
  title: zrok Client
  version: 1.0.0
paths:
  /:
    get:
      tags:
        - metadata
      responses:
        200:
          description: Retrieve the current server version
          schema:
            $ref: "#/definitions/version"
definitions:
  version:
    type: object
    properties:
      version:
        type: string
        minLength: 1
produces:
- application/zrok.client.v1+json
consumes:
- application/zrok.client.v1+json
schemes:
- http
swagger: "2.0"
