name: Build/Release Node SDK

on:
  release:
    types: [ published ]
  push:
    branches: [ main ]
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build for Node-${{ matrix.node_ver }} ${{ matrix.config.target }}/${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.os }}

    env:
      BUILD_NUMBER: ${{ github.run_number }}
      AWS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    
    strategy:
      matrix:
        config:
          - { os: ubuntu-20.04,   target: "linux", arch: "x64" }
        node_ver: [ 20 ]
      fail-fast: false

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Node Version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_ver }}

    - name: Get current date
      id: date
      run: echo "date=$(date)" >> $GITHUB_OUTPUT

    - name: Build NodeJS-SDK
      run: |
        cd ${{ runner.workspace }}/${{ github.event.repository.name }}/sdk/nodejs/sdk
        npm install
        npm run build
      env:
        BUILD_DATE: ${{ steps.date.outputs.date }}

    - name: NPM Publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        access: public
      if: |
        startsWith(github.ref, 'refs/tags/')